[package]
name = "spring-crabs"
version = "0.0.1"

[dependencies]
glium = "0.15.0"
cgmath = "^0.12"

[replace]
"glutin:0.6.1" = { git = "https://github.com/badboy/glutin", branch = "emscripten-fix" }
"backtrace:0.2.3" = { git = "https://github.com/badboy/backtrace-rs", branch = "emscripten-fix" }

